---
services:
  # Since the latest version of MySQL is set to use default SSL certificate files,
  # that SSL certificate isn't able to set CN, we need to create our own SSL certificate files.
  ssl_certificate:
    environment:
      DOMAIN_NAME: database
      SUPPORT_ROOT_DOMAIN: true
    image: futureys/ssl-certificate:2.1.1
    volumes:
      - pki:/etc/pki
  database:
    command:
      - --ssl-ca=/etc/pki/CA/cacert-database.pem
      - --ssl-cert=/etc/pki/tls/certs/servercert-database.pem
      - --ssl-key=/etc/pki/tls/private/serverkey-database.pem
      # - --mysql-native-password=ON
      # - --default-authentication-plugin=mysql_native_password
    depends_on:
      - ssl_certificate
    entrypoint: setup-certificate.sh
    environment:
      DOMAIN_NAME: database
      MYSQL_ROOT_PASSWORD: examplepass
    image: mysql:${MYSQL_VERSION:?err}
    volumes:
      # To enable SSL for MySQL serving.
      - pki:/etc/pki
      # To wait for creating certificate and setup it.
      - ./database_entrypoint/setup-certificate.sh:/usr/local/bin/setup-certificate.sh

  phpunit-wordpress-plugin:
    command:
      - sh
      - -c
      - "phpunit --version && phpcs --version"
    depends_on:
      - database
      - ssl_certificate
    environment:
      DATABASE_PASSWORD: examplepass
    volumes:
      # To enable SSL for MySQL serving.
      - pki:/etc/pki
volumes:
  pki:
