---
version: '3.6'
services:
  database:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    image: mysql:${MYSQL_VERSION:?err}

  sut:
    build:
      context: .
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION:?err}
        PHP_IMAGE_TAG: ${PHP_IMAGE_TAG:?err}
        PHP_UNIT_VERSION: ${PHP_UNIT_VERSION:-}
    command:
      - sh
      - -c
      - "phpunit --version && phpcs --version"
    depends_on:
      - database
    environment:
      DATABASE_PASSWORD: examplepass
    image: futureys/phpunit-wordpress-plugin:${WORDPRESS_VERSION}-php${PHP_IMAGE_TAG}
