#!/bin/bash
# @see https://docs.docker.com/docker-hub/builds/advanced/#build-hook-examples

# Runs matrix build.
# @see https://blog.thesparktree.com/docker-hub-matrix-builds
run_matrix_build() {
    while read software_version_line; do
        wordpress_version=$(echo "${software_version_line}" | cut -d ',' -f 1)
        php_image_tag=$(echo "${software_version_line}" | cut -d ',' -f 2)
        image_tag="${DOCKER_REPO}:${wordpress_version}-php${php_image_tag}"

        docker build -f "${DOCKERFILE_PATH}" --build-arg WORDPRESS_VERSION="${wordpress_version}" --build-arg PHP_IMAGE_TAG="${php_image_tag}" -t "${image_tag}" .
    done < software-versions.txt
}

run_matrix_build
