#!/bin/bash
# @see https://docs.docker.com/docker-hub/builds/advanced/#build-hook-examples

run_matrix_test() {
    test_path='docker-compose.test.yml'

    while read software_version_line; do
        wordpress_version=$(echo "${software_version_line}" | cut -d ',' -f 1)
        php_image_tag=$(echo "${software_version_line}" | cut -d ',' -f 2)
        mysql_version=$(echo "${software_version_line}" | cut -d ',' -f 3)
        echo -e "WORDPRESS_VERSION=${wordpress_version}\nPHP_IMAGE_TAG=${php_image_tag}\nMYSQL_VERSION=${mysql_version}\n" > .env

        echo "Starting Test in ${test_path}..."
        docker-compose -f "${test_path}" pull

        echo "building ${test_path}"
        docker-compose -f "${test_path}" -p ${BUILD_CODE} build

        echo "starting "sut" service in ${test_path}"
        docker-compose -f "${test_path}" -p ${BUILD_CODE} up sut
        exit_code=$?

        docker-compose -f "${test_path}" -p "${BUILD_CODE}" rm --force -v

        rm -f .env

        if [ ${exit_code} -ne 0 ]; then
            echo "building ${test_path} (${exit_code})"
            exit 1
        fi
        echo "Tests in ${test_path} succeeded"
    done < software-versions.txt
}

run_matrix_test
